### ISSUE TITLE
Proposal: change libconfuse into a GitHub org.

### ISSUE THREAD

**Issue by troglobit** [libconfuse/libconfuse#144]
@martinh It would be great if we could change the libConfuse project into a GitHub organization.  Now with Microsoft at the helm many of the formerly locked down features are available for free to us mere humans.

We did the same for https://github.com/libnet/libnet/ which opened up for the org. to subscribe to services like https://codedocs.xyz/libnet/libnet/ for the Doxygen docs and Travis-CI + Appveyor for automated build+testing on Linux/macOS + Windows.

We also get automatic redirect from our current URL to the new.

What do you think, Martin?

**Comment by troglobit** [comment]
Awesome, we have a libConfuse org, thank you @martinh :partying_face: :clinking_glasses: 

Now, I don't have the repo rights for the current project to move it to the org.  Maybe you could fix that too, now that you're on a roll? :smiley:

**Comment by martinh** [comment]
goodbye martinh/libconfuse.
hello libconfuse/libconfuse.

**Comment by troglobit** [comment]
Nice work, thank you! :)
