### ISSUE TITLE
Allow binary integers/bitmasks

### ISSUE THREAD

**Issue by Thomseeen** [libconfuse/libconfuse#145]
Maybe this is already possible and I just didn't find how... but, if not:
It would be nice to be able to define integers in the config file using standard C notiation for hexadecimal and binary, e.g.:
```
CONFIG_ADC_PIN_MASK = 0b0010
CONFIG_ADC_MAX_IDX = 0xFFFF
```

**Comment by troglobit** [comment]
A `CFG_INT` is converted from string to int using [strtol(3)](https://www.man7.org/linux/man-pages/man3/strtol.3.html), so 0xffff works, but not 0b0010. Patches or pull requests are welcome.

**Comment by unmanned-player** [comment]
Pull Request [151](https://github.com/libconfuse/libconfuse/pull/151) should do this.
