### ISSUE TITLE
'no such option ...' error for options in section with CFGF_KEYSTRVAL flag

### ISSUE THREAD

**Issue by LonerDan** [libconfuse/libconfuse#160]
Hello,
I have a section with key=value pairs unknown beforehand so I have it defined with the CFGF_KEYSTRVAL flag. However, it still prints an error message 'no such option ...'  for each entry in that section during parsing. The same thing happens in the examples/env program if you want to check.
I think this is not desirable behavior and can be quite problematic with large freeform sections which would cause the parser to flood the console with errors.

**Comment by troglobit** [comment]
Please enclose the full error message and version of libConfuse in your bug report.

**Comment by LonerDan** [comment]
I am using libconfuse release version 3.3.
When I build it and run env from the examples, I get the following:
![](https://user-images.githubusercontent.com/11718484/142830155-6bfe56a5-c5d2-41c7-9685-b8c03e1f58e0.png)
____________________________
My build setup:
Ubuntu 18.04 LTS in WSL2
GCC 7.5.0
binutils 2.30
autoconf 2.69
automake 1.15.1
libtool 2.4.6
gettext 0.19.8.1
autopoint 0.19.8.1
flex 2.6.4

**Comment by troglobit** [comment]
OK, now I see what you mean.  Yeah, we should probably try to hide that from such sections.

**Comment by LonerDan** [comment]
Related to #130
