### ISSUE TITLE
Get all unknown options

### ISSUE THREAD

**Issue by Trumeet** [libconfuse/libconfuse#162]
Hi, is it possible to get all unknown options in a section? I need to pass them to other programs to customize. Thank you.

**Comment by troglobit** [comment]
Not that I know of, no.

**Comment by Trumeet** [comment]
> Not that I know of, no.

@troglobit Would you consider adding this feature in the future? It would be really helpful.

**Comment by troglobit** [comment]
I have no need for such a feature myself, so no. But that's not to say it couldn't be added by someone else, or even you.  There are, however, many use cases to consider when making changes to the code base, so it's not for the faint of heart.

I "recently" added support for the `CFGF_KEYSTRVAL` flag, it's a section flag which allows you to create things like:
```
env {
  foo="some string"
  bar="other value"
}
```
where `foo` and `bar` are unknown to the parser.  Maybe that's what you want, I don't know, your question was very generic.

If not, then you (or someone else inclined) could have a look at that commit to see what I did. However, I think the best option would be to add callback functionality, for the parser to call on options in `CFGF_IGNORE_UNKNOWN` sections.

**Comment by Trumeet** [comment]
@troglobit Wow, thank you. The `CFGF_KEYSTRVAL` feature is exactly what I needed for now.
