### ISSUE TITLE
integer value for option 'CFG_INT' is out of range

### ISSUE THREAD

**Issue by mik1234mc** [libconfuse/libconfuse#171]
Hi all,

encountered weird behavior for parameter defined as CFG_INT. If I set to a value =>0x80000000 on 32bit system. Libconfuse (3.3) gives me `conf.conf:17: integer value for option 'parameter' is out of range`. What I am doing wrong that integer value is not valid?

Thanks,
Mike

**Comment by troglobit** [comment]
`CFG_INT` is a signed integer. On a 32-bit system that means the maximum value is 0x7fffffff (2147483647).

See #11 for more information.

**Comment by mik1234mc** [comment]
thank you for your answer. So, it turns out to be hex radix error; if I set -2147483648, it gives me 0x80000000. 0x80000000 is valid signed 32bit integer.

**Comment by troglobit** [comment]
Yeah, we use `strtol()` to convert the input value. The syntax 0nnnnn, 0xnnnn, 0bnnnn, or nnnn is only syntactic sugar to establish the radix argument to that function.  when you input 0x80000000 try to convert a postive hexadecimal value that is greater than the datatype can store.  The value 0x7fffffff is the largest positive value you can store.
