### ISSUE TITLE
Add thread-safe error handler for C++ to library

### ISSUE THREAD

**Issue by anonymous09** [libconfuse/libconfuse#77]
Good day. I'm using libconfuse in C++ project. One issue that make me sad is that I cannot set custom thread-safe error handler which has access to my class/struct members.

My proposal: make possibility to set custom error handler with modern C++ std::functions.

"#ifdef __cplusplus" can help you?

**Comment by troglobit** [comment]
Good idea! Care to whip up a pull request with a proposal?

**Comment by anonymous09** [comment]
Well, I will try to create.

**Comment by troglobit** [comment]
@anonymous09 Did you find the `cfg_set_error_function()`?

**Comment by bharsaklemukesh975** [comment]
Can I work on this?

**Comment by troglobit** [comment]
@bharsaklemukesh975 sure, anyone can pitch in and the previous effort seem to have stalled.

**Comment by bharsaklemukesh975** [comment]
Hello @troglobit, I can see cfg_set_error_function(), so the task it to make it thread safe, right?

**Comment by troglobit** [comment]
As long as each thread has its own `cfg_t` the `cfg_set_error_function()` (and others) should be thread safe by design.  The original reporter said: "I cannot set custom thread-safe error handler which has access to my class/struct members.", which I assume was something specific to C++, which I have next to no knowledge in.  So your guess is as good as mine here.

**Comment by bharsaklemukesh975** [comment]
Ideally, he should pass it as an argument(pointer to the struct/class) to the function and should be able to access the data.
For this c library, the request looks like adding a C++ feature to this which it has already in c.

**Comment by troglobit** [comment]
Yeah I never really understood it either.  The `cfg_set_error_function()` makes it possible to define your own callback that libConfuse will use instead of the default:

     void (*cfg_errfunc_t)(cfg_t *cfg, const char *fmt, va_list ap);

If that callback is a class method it would get access to the data in question, right?

**Comment by troglobit** [comment]
As I suspected, well then I guess we can close this one as a no-op/rtfm? 😃👍

**Comment by bharsaklemukesh975** [comment]
yes, we can close this!👍
